# Generated by Django 5.0 on 2024-01-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ['name'], 'verbose_name': 'Локации', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AddField(
            model_name='locations',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='locations',
            index=models.Index(fields=['name'], name='weather_loc_name_2a97bb_idx'),
        ),
    ]
