# Generated by Django 5.0 on 2024-01-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_locations_options_locations_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
