# Generated by Django 5.0 on 2024-01-10 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_locations_latitude_alter_locations_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locations',
            unique_together={('name', 'latitude', 'longitude', 'user_id')},
        ),
    ]
