desc_dict = {
    'thunderstorm with light rain': 'гроза с небольшим дождем',
    'thunderstorm with rain': 'гроза с дождем',
    'thunderstorm with heavy rain': 'гроза с проливным дождем',
    'light thunderstorm': 'легкая гроза',
    'thunderstorm': 'гроза',
    'heavy thunderstorm': 'сильная гроза',
    'ragged thunderstorm': 'рваная гроза',
    'thunderstorm with light drizzle': 'гроза с легким моросящим дождем',
    'thunderstorm with drizzle': 'гроза с моросящим дождем',
    'thunderstorm with heavy drizzle': 'гроза с сильным моросящим дождем',
    'light intensity drizzle': 'моросящий дождь небольшой интенсивности',
    'drizzle': 'морось',
    'heavy intensity drizzle': 'сильный моросящий дождь',
    'light intensity drizzle rain': 'легкой интенсивности моросящий дождь',
    'drizzle rain': 'моросящий дождь',
    'heavy intensity drizzle rain': 'сильный моросящий дождь',
    'shower rain and drizzle': 'ливень, дождь и морось',
    'heavy shower rain and drizzle': 'сильный ливень и морось',
    'shower drizzle': 'моросящий ливень',
    'light rain': 'небольшой дождь',
    'moderate rain': 'умеренный дождь',
    'heavy intensity rain': 'сильный дождь',
    'very heavy rain': 'очень сильный дождь',
    'extreme rain': 'экстремально сильный дождь',
    'freezing rain': 'ледяной дождь',
    'light intensity shower rain': 'легкой интенсивности ливень',
    'shower rain': 'ливень',
    'heavy intensity shower rain': 'ливень сильной интенсивности',
    'ragged shower rain': 'рваный ливень',
    'light snow': 'легкий снег',
    'snow': 'снег',
    'heavy snow': 'сильный снегопад',
    'sleet': 'слякоть',
    'light shower sleet': 'небольшой дождь с мокрым снегом',
    'shower sleet': 'ливень с мокрым снегом',
    'light rain and snow': 'небольшой дождь и снег',
    'rain and snow': 'дождь и снег',
    'light shower snow': 'легкий дождь со снегом',
    'shower snow': 'ливень со снегом',
    'heavy shower snow': 'сильный ливень со снегом',
    'mist': 'туман',
    'smoke': 'дым',
    'haze': 'легкий туман',
    'sand/dust whirls': 'вихри песка/пыли',
    'fog': 'дымка',
    'sand': 'песчаная',
    'dust': 'пыль',
    'volcanic ash': 'вулканический пепел',
    'squalls': 'шквалы',
    'tornado': 'торнадо',
    'clear sky': 'ясное небо',
    'few clouds': 'небольшая облачность',
    'scattered clouds': 'рассеянные облака',
    'broken clouds': 'разорванные облака',
    'overcast clouds': 'затянуто облаками',
}